### PR TITLE
Fix: Ant Menu Deprecated Warnings

### LINKED ISSUE #237: Fix Ant Menu Deprecated Warnings
**Is your feature request related to a problem? Please describe.**
Ant Design Menu component suggest to use `items` instead of `children` for better performace.

**Describe the solution you'd like**
Check sidebar and Dropdowns page and fix console warnings.

### PR DESCRIPTION
**Pull request by UtkarshM-hub**
# Description

Fixes #237

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

* by running the project locally
* making sure that the routes are working
* making sure that the issue is resolved by checking console logs

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by UtkarshM-hub** [comment]
@alexanderrudnik

**Comment by leineveber** [comment]
Hello @UtkarshM-hub,

Thanks for taking a part in the development. 

We adhere to certain code quality throughout the project. Those Ant Menus should be fixed everywhere we use them and not only in the sidebar. Also, looks like translation is broken, please use translation functions

**Comment by UtkarshM-hub** [comment]
hey @leineveber,
I tried fixing it but I think I am having problems on my side and not able to pull that off

**Comment by leineveber** [comment]
Closing due to inactivity

**Pull request closed without merging**
